package POJOS;
// Generated Aug 10, 2020 11:54:03 AM by Hibernate Tools 4.3.1



/**
 * Bookings generated by hbm2java
 */
public class Bookings  implements java.io.Serializable {


     private int bookingId;
     private Cinema cinema;
     private Customer customer;
     private Movies movies;
     private String seat;

    public Bookings() {
    }

    public Bookings(int bookingId, Cinema cinema, Customer customer, Movies movies, String seat) {
       this.bookingId = bookingId;
       this.cinema = cinema;
       this.customer = customer;
       this.movies = movies;
       this.seat = seat;
    }
   
    public int getBookingId() {
        return this.bookingId;
    }
    
    public void setBookingId(int bookingId) {
        this.bookingId = bookingId;
    }
    public Cinema getCinema() {
        return this.cinema;
    }
    
    public void setCinema(Cinema cinema) {
        this.cinema = cinema;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Movies getMovies() {
        return this.movies;
    }
    
    public void setMovies(Movies movies) {
        this.movies = movies;
    }
    public String getSeat() {
        return this.seat;
    }
    
    public void setSeat(String seat) {
        this.seat = seat;
    }




}


