package POJOS;
// Generated Aug 10, 2020 11:54:03 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Manager generated by hbm2java
 */
public class Manager  implements java.io.Serializable {


     private int managerId;
     private String managerName;
     private String managerNumber;
     private String username;
     private String password;
     private Set cinemas = new HashSet(0);

    public Manager() {
    }

	
    public Manager(int managerId, String managerName, String managerNumber, String username, String password) {
        this.managerId = managerId;
        this.managerName = managerName;
        this.managerNumber = managerNumber;
        this.username = username;
        this.password = password;
    }
    public Manager(int managerId, String managerName, String managerNumber, String username, String password, Set cinemas) {
       this.managerId = managerId;
       this.managerName = managerName;
       this.managerNumber = managerNumber;
       this.username = username;
       this.password = password;
       this.cinemas = cinemas;
    }
   
    public int getManagerId() {
        return this.managerId;
    }
    
    public void setManagerId(int managerId) {
        this.managerId = managerId;
    }
    public String getManagerName() {
        return this.managerName;
    }
    
    public void setManagerName(String managerName) {
        this.managerName = managerName;
    }
    public String getManagerNumber() {
        return this.managerNumber;
    }
    
    public void setManagerNumber(String managerNumber) {
        this.managerNumber = managerNumber;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getCinemas() {
        return this.cinemas;
    }
    
    public void setCinemas(Set cinemas) {
        this.cinemas = cinemas;
    }




}


