package POJOS;
// Generated Aug 10, 2020 11:54:03 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Movies generated by hbm2java
 */
public class Movies  implements java.io.Serializable {


     private String movieName;
     private String genre;
     private byte showing;
     private Set bookingses = new HashSet(0);

    public Movies() {
    }

	
    public Movies(String movieName, String genre, byte showing) {
        this.movieName = movieName;
        this.genre = genre;
        this.showing = showing;
    }
    public Movies(String movieName, String genre, byte showing, Set bookingses) {
       this.movieName = movieName;
       this.genre = genre;
       this.showing = showing;
       this.bookingses = bookingses;
    }
   
    public String getMovieName() {
        return this.movieName;
    }
    
    public void setMovieName(String movieName) {
        this.movieName = movieName;
    }
    public String getGenre() {
        return this.genre;
    }
    
    public void setGenre(String genre) {
        this.genre = genre;
    }
    public byte getShowing() {
        return this.showing;
    }
    
    public void setShowing(byte showing) {
        this.showing = showing;
    }
    public Set getBookingses() {
        return this.bookingses;
    }
    
    public void setBookingses(Set bookingses) {
        this.bookingses = bookingses;
    }




}


