/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mzamomstha.registration;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Enzo
 */
public class LearnerDatabase extends javax.swing.JFrame {
    
    //Display Learner Database in tabel
    public ArrayList<MySQlToLearnerDatabase> learnerDatabase() {
        ArrayList<MySQlToLearnerDatabase> learnersDatabase = new ArrayList<>();
        
        Connection conn = null;
        try {

            conn = DriverManager.getConnection(
               "jdbc:mysql://localhost:3306/mzamomtsha_registration","root", "root");
            
        String query = "SELECT * FROM mzamomtsha_registration.learner;";
        Statement stmnt = conn.createStatement();
        ResultSet rs = stmnt.executeQuery(query);
        MySQlToLearnerDatabase sqlConnection;
        
        while (rs.next()) {
            sqlConnection = new MySQlToLearnerDatabase(rs.getInt("ID"), rs.getString("name"), rs.getString("surname"), rs.getString("gender"), rs.getString("DoB"), rs.getString("number"));
            learnersDatabase.add(sqlConnection);
        }
            
        } catch (SQLException e) {
        }
        return learnersDatabase;
    }
    
    public final void showLearnersDatabase() {
        ArrayList<MySQlToLearnerDatabase> learnerList = learnerDatabase();
        DefaultTableModel model = (DefaultTableModel)tblLearnerDatabase.getModel();
        Object[] row = new Object[6];
        
        for (int i = 0; i < learnerList.size(); i++) {
            row[0] = learnerList.get(i).getID();
            row[1] = learnerList.get(i).getName();
            row[2] = learnerList.get(i).getSurname();
            row[3] = learnerList.get(i).getGender();
            row[4] = learnerList.get(i).getDoB();
            row[5] = learnerList.get(i).getNumber();
            model.addColumn(row);
        }
        
    }
    
    //End of the Connection to table
    
    //go back to Login Page
    public Login login;
    
    public void setLogin (Login login) {
        this.login = login;
    }
    
    public void backToLogin() {
        this.dispose();
        new Login().setVisible(true);
    }
    
    //go to Teacher Database
    public TeacherDatabase teacherDatabase;
    
    public void setTeacherDatabase (TeacherDatabase teacherDatabase) {
        this.teacherDatabase = teacherDatabase;
    }
    
    public void openTeacherDatabase() {
        this.dispose();
        new TeacherDatabase().setVisible(true);
    }
    
    //go to Parent Database
    public ParentDatabase parentDatabase;
    
    public void setParentDatabase (ParentDatabase parentDatabase) {
        this.parentDatabase = parentDatabase;
    }
    
    public void openParentDatabase() {
        this.dispose();
        new ParentDatabase().setVisible(true);
    }
    
    //go to Add User Page
    public UserAdd addUserPage;
    
    public void setUserPage (UserAdd addUserPage) {
        this.addUserPage = addUserPage;
    }
    
    public void openUserAddPage() {
        this.dispose();
        new UserAdd().setVisible(true);
    }
    
    /**
     * Creates new form LearnerDatabase
     */
    public LearnerDatabase() {
        initComponents();
        showLearnersDatabase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblLearnerDatabase = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        btnTeacher = new javax.swing.JButton();
        btnParent = new javax.swing.JButton();
        btnAddUserPage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Learner Database");
        setName("learnerDatabaseFrame"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblLearnerDatabase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Surname", "Gender", "Date of Birth", "Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLearnerDatabase.setToolTipText("To be implemented later");
        jScrollPane1.setViewportView(tblLearnerDatabase);

        btnRefresh.setText("Refresh");
        btnRefresh.setToolTipText("To be implemented later");

        btnTeacher.setText("Teacher Table");
        btnTeacher.setToolTipText("");
        btnTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherActionPerformed(evt);
            }
        });

        btnParent.setText("Parent Table");
        btnParent.setToolTipText("");
        btnParent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParentActionPerformed(evt);
            }
        });

        btnAddUserPage.setText("Add User Page");
        btnAddUserPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserPageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAddUserPage)
                        .addGap(68, 68, 68)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(95, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnParent)
                        .addGap(129, 129, 129)
                        .addComponent(btnTeacher)
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh)
                    .addComponent(btnTeacher)
                    .addComponent(btnParent))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddUserPage)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Connection conn = null;
        
        try {
            conn = DriverManager.getConnection(
               "jdbc:mysql://localhost:3306/mzamomtsha_registration","root", "root");
        } catch (SQLException e) {
        }
  
    }//GEN-LAST:event_formWindowOpened

    private void btnParentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParentActionPerformed
        openParentDatabase();
    }//GEN-LAST:event_btnParentActionPerformed

    private void btnTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherActionPerformed
        openTeacherDatabase();
    }//GEN-LAST:event_btnTeacherActionPerformed
        
    private void btnAddUserPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserPageActionPerformed
        openUserAddPage();
    }//GEN-LAST:event_btnAddUserPageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LearnerDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LearnerDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LearnerDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LearnerDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LearnerDatabase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUserPage;
    private javax.swing.JButton btnParent;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTeacher;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLearnerDatabase;
    // End of variables declaration//GEN-END:variables

}
