/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mzamomstha.registration;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Enzo
 */
public class LearnerDatabase extends javax.swing.JFrame {    
    public void Update() {
        for (int i = 0; i <= 100; i++) {           
           progEnrolled.setValue(i);          
           progEnrolled.setVisible(true);
           
           try {
                Thread.sleep(10);
            } catch (InterruptedException ex) {
                Logger.getLogger(LearnerDatabase.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    //Display Learner Database in tabel
    public ArrayList<MySQlToLearnerDatabase> learnerDatabase() {
        ArrayList<MySQlToLearnerDatabase> learnersDatabase = new ArrayList<>();
        
        Connection conn = null;
        try {

            conn = DriverManager.getConnection(
               "jdbc:mysql://localhost:3306/mzamomtsha_registration","root", "root");
            
        String query = "SELECT * FROM learner;";
        Statement stmnt = conn.createStatement();
        ResultSet rs = stmnt.executeQuery(query);
        MySQlToLearnerDatabase sqlConnection;
        
        while (rs.next()) {
            sqlConnection = new MySQlToLearnerDatabase(rs.getInt("ID"), rs.getString("Name"), rs.getString("Surname"), rs.getString("Gender"), rs.getString("Date_of_Birth"), rs.getString("Number"));
            learnersDatabase.add(sqlConnection);
        }
            
        } catch (SQLException e) {
        }
        return learnersDatabase;
    }
    
    public final void showLearnersDatabase() {
        ArrayList<MySQlToLearnerDatabase> learnerList = learnerDatabase();
        DefaultTableModel model = (DefaultTableModel)tblLearnerDatabase.getModel();
        Object[] row = new Object[6];
        
        for (int i = 0; i < learnerList.size(); i++) {
            row[0] = learnerList.get(i).getID();
            row[1] = learnerList.get(i).getName();
            row[2] = learnerList.get(i).getSurname();
            row[3] = learnerList.get(i).getGender();
            row[4] = learnerList.get(i).getDoB();
            row[5] = learnerList.get(i).getNumber();
            model.addColumn(row);
        }
        
    }
    
    //End of the Connection to table
    
    //go back to Login Page
    public Login login;
    
    public void setLogin (Login login) {
        this.login = login;
    }
    
    public void backToLogin() {
        this.dispose();
        new Login().setVisible(true);
    }
    
    //go to Teacher Database
    public TeacherDatabase teacherDatabase;
    
    public void setTeacherDatabase (TeacherDatabase teacherDatabase) {
        this.teacherDatabase = teacherDatabase;
    }
    
    public void openTeacherDatabase() {
        this.dispose();
        new TeacherDatabase().setVisible(true);
    }
    
    //go to Parent Database
    public ParentDatabase parentDatabase;
    
    public void setParentDatabase (ParentDatabase parentDatabase) {
        this.parentDatabase = parentDatabase;
    }
    
    public void openParentDatabase() {
        this.dispose();
        new ParentDatabase().setVisible(true);
    }
    
    //go to Add User Page
    public UserAdd addUserPage;
    
    public void setUserPage (UserAdd addUserPage) {
        this.addUserPage = addUserPage;
    }
    
    public void openUserAddPage() {
        this.dispose();
        new UserAdd().setVisible(true);
    }
    
    /**
     * Creates new form LearnerDatabase
     */
    public LearnerDatabase() {       
        initComponents();
        learnerDatabase();
        showLearnersDatabase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLearnerDatabase = new javax.swing.JTable();
        btnTeacher = new javax.swing.JButton();
        btnParent = new javax.swing.JButton();
        btnAddUserPage = new javax.swing.JButton();
        btnSort = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        progEnrolled = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Learner Database");
        setName("learnerDatabaseFrame"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblLearnerDatabase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Surname", "Gender", "Date of Birth", "Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblLearnerDatabase.setToolTipText("To be implemented later");
        jScrollPane1.setViewportView(tblLearnerDatabase);

        btnTeacher.setText("Teacher Table");
        btnTeacher.setToolTipText("");
        btnTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherActionPerformed(evt);
            }
        });

        btnParent.setText("Parent Table");
        btnParent.setToolTipText("");
        btnParent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParentActionPerformed(evt);
            }
        });

        btnAddUserPage.setText("Add User Page");
        btnAddUserPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserPageActionPerformed(evt);
            }
        });

        btnSort.setText("Percentage of Learners Enrolled");
        btnSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortActionPerformed(evt);
            }
        });

        jLabel2.setText("Sort by?");

        jLabel3.setText("Subjects");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afrikaans", "English", "Mathematics Lit.", "Mathematics", "Life Skills", "Arts", "Drama", "IT" }));

        progEnrolled.setToolTipText("Amount of Learners Enrolled");
        progEnrolled.setAutoscrolls(true);
        progEnrolled.setStringPainted(true);

        jLabel4.setText("Age Group & Phases");

        jRadioButton1.setText("6-9");

        jRadioButton2.setText("10-14");

        jRadioButton3.setText("15-17");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(123, 123, 123)
                        .addComponent(btnAddUserPage)
                        .addGap(100, 100, 100)
                        .addComponent(btnParent)
                        .addGap(100, 100, 100)
                        .addComponent(btnTeacher)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 788, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton3)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSort)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(progEnrolled, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTeacher)
                    .addComponent(btnParent)
                    .addComponent(btnAddUserPage)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(progEnrolled, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton3)
                        .addGap(45, 45, 45)
                        .addComponent(btnSort)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Connection conn = null;
        
        try {
            conn = DriverManager.getConnection(
               "jdbc:mysql://localhost:3306/mzamomtsha_registration","root", "root");
        } catch (SQLException e) {
        }
  
    }//GEN-LAST:event_formWindowOpened

    private void btnParentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParentActionPerformed
        openParentDatabase();
    }//GEN-LAST:event_btnParentActionPerformed

    private void btnTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherActionPerformed
        openTeacherDatabase();
    }//GEN-LAST:event_btnTeacherActionPerformed
        
    private void btnAddUserPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserPageActionPerformed
        openUserAddPage();
    }//GEN-LAST:event_btnAddUserPageActionPerformed

    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortActionPerformed
        Update();
    }//GEN-LAST:event_btnSortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LearnerDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LearnerDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LearnerDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LearnerDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LearnerDatabase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUserPage;
    private javax.swing.JButton btnParent;
    private javax.swing.JButton btnSort;
    private javax.swing.JButton btnTeacher;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JProgressBar progEnrolled;
    private javax.swing.JTable tblLearnerDatabase;
    // End of variables declaration//GEN-END:variables

}
