/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mzamomstha.registration;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Enzo
 */
public class RegistrationForm extends javax.swing.JFrame {
    
    private static final String CREATE_TABLE_SQL="CREATE TABLE staff ("
                    + "UserID INT NOT NULL,"
                    + "Name VARCHAR(45) NOT NULL,"
                    + "Surname VARCHAR(45) NOT NULL,"
                    + "Date_Of_Birth DATE NOT NULL,"
                    + "Number MEDUIMTEXT NOT NULL,"
                    + "Admin TINYINT(1) NOT NULL,"
                    + "PRIMARY KEY (PlayerID))";
    
    public RegistrationForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        btnAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        edtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        edtName = new javax.swing.JTextField();
        edtSurname = new javax.swing.JTextField();
        edtDoB = new javax.swing.JTextField();
        edtNumber = new javax.swing.JTextField();
        rbtAdmin = new javax.swing.JRadioButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAdd.setText("Add User");
        btnAdd.setToolTipText("Click to add the user to the Database");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel1.setText("ID :");
        jLabel1.setName("ID"); // NOI18N

        edtID.setToolTipText("Enter the UserID here");

        jLabel2.setText("Name:");
        jLabel2.setName("Name"); // NOI18N

        jLabel3.setText("Surname:");
        jLabel3.setName("Surname"); // NOI18N

        jLabel4.setText("Date of Birth:");

        jLabel5.setText("Cell Phone Number:");
        jLabel5.setName("Number"); // NOI18N

        jLabel6.setText("Admin?");
        jLabel6.setName("Admin"); // NOI18N

        edtName.setToolTipText("Enter the User's Name here");

        edtSurname.setToolTipText("Enter the User's Surname here");

        edtDoB.setToolTipText("Enter the User's Date of Birth Here (yyyy/mm/dd)");

        edtNumber.setToolTipText("Enter the User's Cell Phone Number here");
        edtNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNumberActionPerformed(evt);
            }
        });

        rbtAdmin.setText("Yes");
        rbtAdmin.setToolTipText("Tick if it is an Admin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtDoB, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtName, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtID, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtAdmin)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btnAdd)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {edtDoB, edtID, edtName, edtNumber, edtSurname});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(edtDoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(edtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rbtAdmin))
                .addGap(24, 24, 24)
                .addComponent(btnAdd)
                .addGap(30, 30, 30))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {edtDoB, edtID, edtName, edtNumber, edtSurname, jLabel1, jLabel2, jLabel3, jLabel5, jLabel6});

        btnAdd.getAccessibleContext().setAccessibleName("btnAdd");
        jLabel1.getAccessibleContext().setAccessibleName("lblID");
        edtID.getAccessibleContext().setAccessibleName("edtUserID");
        jLabel2.getAccessibleContext().setAccessibleName("lblName");
        jLabel3.getAccessibleContext().setAccessibleName("lblSurname");
        jLabel5.getAccessibleContext().setAccessibleName("lblNumber");
        jLabel6.getAccessibleContext().setAccessibleName("lblAdmin");
        edtName.getAccessibleContext().setAccessibleName("edtName");
        edtSurname.getAccessibleContext().setAccessibleName("edtSurname");
        edtDoB.getAccessibleContext().setAccessibleName("edtDoB");
        edtNumber.getAccessibleContext().setAccessibleName("edtNumber");
        rbtAdmin.getAccessibleContext().setAccessibleName("rbtAdmin");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNumberActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String userID = edtID.getText();
        String name = edtName.getText();
        String surname = edtSurname.getText();
        String DoB = edtDoB.getText();
        String number = edtNumber.getText();
        String admin = "";
        if (rbtAdmin.isSelected()) {
            admin = "true";
        } else {
            admin = "false";
        }
        
        
        // CONNECTION TO THE DATABSE
        Connection conn = null;
        try {
            conn = DriverManager.getConnection(
               "jdbc:mysql://localhost:3306/mzamomstha_registration","root", "Faders!41");  
             
            Statement stmt = conn.createStatement();
            
            String strSelect = "INSERT INTO staff (UserID, Name, Surname, Date_Of_Birth, Number, Admin) "
                             + "VALUES ('"+userID+"', '"+name+"', '"+surname+"', '"+DoB+"', '"+number+"', "+admin+")";
            
            stmt.executeUpdate(strSelect);
            JOptionPane.showMessageDialog(null, "User Added Successfully!");
            conn.close();
             
        }catch(SQLException e){
        }
        // End OF THE CONNECTION
    }//GEN-LAST:event_btnAddActionPerformed

    
 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
//        Connection conn = null;
//        try {
//            conn = DriverManager.getConnection(
//               "jdbc:mysql://localhost:3306/mzamomstha_registration","root", "Faders!41");  
//             
//            Statement stmt = conn.createStatement();
//            //Create table
//            stmt.executeUpdate(CREATE_TABLE_SQL);
//            System.out.println("Table Created");
//            conn.close();
//             
//        }catch(SQLException e){
//        }
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField edtDoB;
    private javax.swing.JTextField edtID;
    private javax.swing.JTextField edtName;
    private javax.swing.JTextField edtNumber;
    private javax.swing.JTextField edtSurname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JRadioButton rbtAdmin;
    // End of variables declaration//GEN-END:variables
}
