package cinema.management;

import java.io.FileWriter;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.Criteria;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Enzo
 */
public class CreateBooking extends javax.swing.JFrame {

        private static SessionFactory factory;
        public static String receipt = "";
    
    public CreateBooking() {
        initComponents();
        
        if (!Login.isManager) {
            edtCustomerID.setText(String.valueOf(Login.userID));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        edtCustomerID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnBookMovie = new javax.swing.JButton();
        cmbSeat = new javax.swing.JComboBox<>();
        cmbMovie = new javax.swing.JComboBox<>();
        cmbCinema = new javax.swing.JComboBox<>();
        lblBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(495, 260));
        setPreferredSize(new java.awt.Dimension(495, 260));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Customer ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));
        getContentPane().add(edtCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 50, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Cinema:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Movie:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Seat:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        btnBookMovie.setText("Book Movie");
        btnBookMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookMovieActionPerformed(evt);
            }
        });
        getContentPane().add(btnBookMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        cmbSeat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "B10", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10", "D1", "D2", "D3", "D4", "D5", "D6", "D7", "D8", "D9", "D10", "E1", "E2", "E3", "E4", "E5", "E6", "E7", "E8", "E9", "E10", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10" }));
        getContentPane().add(cmbSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 50, -1));

        cmbMovie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Abominable", "All the Bright Places", "Apollo 11", "Black and Blue", "Bloodshot", "Brahms: The Boy II", "Ford v Ferrari", "Fractured", "Gemini Man", "Ghost Stories", "In the Shadow of the Moon", "In the Tall Grass", "Invader Zim: Enter the Florpus", "It Chapter Two", "Jexi", "John Wick: Chapter 3 – Parabellum", "Joker", "Jumanji: The Next Level", "Klaus", "Let it Snow", "Like a Boss", "Line of Duty", "NiNoKuni", "Once Upon a Time in…Hollywood", "Onward", "Parasite", "Playing with Fire", "Spenser Confidential", "Spies in Disguise", "Steven Universe: The Movie", "Survive the Night", "The Adams Family", "The Great Hack", "The Kissing Booth 2", "The Last Days of American Crime", "The Last Thing He Wanted", "The Lion King Live Action", "The Main Event", "The Willoughbys", "The Wrong Missy", " " }));
        getContentPane().add(cmbMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 220, -1));

        cmbCinema.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cinema X 1", "Cinema X 2", "Cinema X 3", "Cinema X 4", "Cinema X 5", "Cinema X 6", "Cinema X 7", "Cinema X 8", "Cinema X 9", "Colosseum 1", "Colosseum 2", "Colosseum 3", "Colosseum 4", "Colosseum 5", "Colosseum 6", "Colosseum 7", "Colosseum 8", "Colosseum 9", "Nu Metro 1", "Nu Metro 2", "Nu Metro 3", "Nu Metro 4", "Nu Metro 5", "Nu Metro 6", "Nu Metro 7", "Nu Metro 8", "Nu Metro 9", "Ster Kinekor 1", "Ster Kinekor 2", "Ster Kinekor 3", "Ster Kinekor 4", "Ster Kinekor 5", "Ster Kinekor 6", "Ster Kinekor 7", "Ster Kinekor 8", "Ster Kinekor 9" }));
        getContentPane().add(cmbCinema, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        lblBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login_screen.jpg"))); // NOI18N
        getContentPane().add(lblBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 260));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        dispose();
        new MainInterface().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBookMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookMovieActionPerformed
        if (!checkNull()) {
            int customerID = Integer.valueOf(edtCustomerID.getText());
            String cinema = cmbCinema.getSelectedItem().toString();
            String seat = cmbSeat.getSelectedItem().toString();
            String movie = cmbMovie.getSelectedItem().toString();
            int id = 0;
            
            factory = new Configuration().configure().buildSessionFactory();
            Session session = factory.openSession();
            Transaction tx = null;
            
            try {
                tx = session.beginTransaction();
                
                Criteria critCus = null;
                Criteria critMan = null;
                List stuff = null;




                critCus = session.createCriteria(POJOS.Bookings.class);
                stuff = critCus.list();
                
                for (Iterator iterator = stuff.iterator(); iterator.hasNext();) {

                    POJOS.Bookings list = (POJOS.Bookings) iterator.next();
                    id = list.getBookingId();
                }
                tx.commit();
                
            } catch (HibernateException e) {
                if (tx != null) {
                    tx.rollback();
                }
                e.printStackTrace();
            }
            tx = session.beginTransaction();
            
            POJOS.Cinema cin = (POJOS.Cinema) session.load(POJOS.Cinema.class,cinema);
            POJOS.Customer cus = (POJOS.Customer) session.load(POJOS.Customer.class,customerID);
            POJOS.Movies movi = (POJOS.Movies) session.load(POJOS.Movies.class,movie);
            POJOS.Bookings booking = new POJOS.Bookings(id + 1, cin, cus, movi, seat);
            session.save(booking);
            tx.commit();
            receipt = "BookingID: "+ String.valueOf(id) +"\nCinema: "+cin.getName()+"\nCustomer ID: "+cus.getId()+"\nMovie: "+movi.getMovieName()+"\nSeat: "+seat;
            
            try {
                FileWriter fw = new FileWriter("Receipt.txt");
                fw.write(receipt);
                fw.close();
            } catch (Exception e) {
            }
            
            session.close();
            JOptionPane.showMessageDialog(null, "Boooking created!");
        }else{
            JOptionPane.showMessageDialog(null, "Please input all the necessary information");
        }
        
    }//GEN-LAST:event_btnBookMovieActionPerformed

    public void addUser(POJOS.Customer myUser) {
        try {
            factory = new Configuration().configure().buildSessionFactory();
        } catch (HibernateException e) {
            System.out.println("You messed up");
            throw new ExceptionInInitializerError(e);
        }
        Session session = factory.openSession();
        Transaction tx = null;
        Integer id = null;

        try {
            tx = session.beginTransaction();
            id = (Integer) session.save(myUser);
            tx.commit();
            JOptionPane.showMessageDialog(null, "Successfully updated database");
        } catch (HibernateException e) {
            if (tx != null) {
                tx.rollback();
            }
        } finally {
            session.close();
        }
    }

    public boolean checkNull() {
        return (edtCustomerID.getText().equals(""));
    }
    
    public void clearTextFields(){
        edtCustomerID.setText("");
        cmbCinema.setSelectedIndex(0);
        cmbMovie.setSelectedIndex(0);
        cmbSeat.setSelectedIndex(0);
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBookMovie;
    private javax.swing.JComboBox<String> cmbCinema;
    private javax.swing.JComboBox<String> cmbMovie;
    private javax.swing.JComboBox<String> cmbSeat;
    private javax.swing.JTextField edtCustomerID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblBG;
    // End of variables declaration//GEN-END:variables
}
