/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hackathon;

/**
 *
 * @author CPTWEX-cpt-066
 */
public class Report_A_Crime extends javax.swing.JFrame {

    /**
     * Creates new form Report_A_Crime
     */
    public Report_A_Crime() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCrime = new javax.swing.JButton();
        btnSusAct = new javax.swing.JButton();
        imgBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setText("Click on The Button Below to report a crime or Suspicios Activity");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, -1));

        btnCrime.setBackground(new java.awt.Color(255, 0, 0));
        btnCrime.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        btnCrime.setText("Crime");
        btnCrime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrimeActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrime, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 200, 230));

        btnSusAct.setBackground(new java.awt.Color(51, 255, 51));
        btnSusAct.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        btnSusAct.setText("Suspicious Activity");
        btnSusAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSusActActionPerformed(evt);
            }
        });
        getContentPane().add(btnSusAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 40, 140, 230));

        imgBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\Enzo\\Pictures\\Wallpapers\\black-dark-3d-low-poly-geometric-background_79145-393.jpg")); // NOI18N
        getContentPane().add(imgBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 290));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrimeActionPerformed
        new Crime().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCrimeActionPerformed

    private void btnSusActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSusActActionPerformed
        new Suspicious_Activity().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSusActActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report_A_Crime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report_A_Crime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report_A_Crime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report_A_Crime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report_A_Crime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrime;
    private javax.swing.JButton btnSusAct;
    private javax.swing.JLabel imgBackground;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
